# Generated by Django 2.2.7 on 2020-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('objectId', models.IntegerField(blank=True, null=True, unique=True)),
                ('apiKey', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
