# Generated by Django 2.2.7 on 2020-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themodel',
            name='apiKey',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
